import { getFile, writeFile } from './github';

export const WORKFLOW_PATH = '.github/workflows/repoflux-agent.yml';

// This will be read from a template file or constant in the real app,
// but hardcoded here for the initial setup.
export const WORKFLOW_YAML_TEMPLATE = `
name: RepoFlux — AI Coding Agent

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'RepoFlux Run ID'
        required: true
        type: string
      prompt:
        description: 'The task for the AI agent'
        required: true
        type: string
      agent_type:
        description: 'Which agent to use (gemini, aider, opencode, crush, qwen, goose, claude-code, codex, aider-ollama)'
        required: false
        default: 'gemini'
        type: string
      state_repo:
        description: 'The state repository name'
        required: true
        type: string
      branch:
        description: 'Branch to run on'
        required: false
        default: 'main'
        type: string
      openrouter_model:
        description: 'Model for OpenRouter agents'
        required: false
        default: 'meta-llama/llama-4-scout:free'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: \${{ inputs.branch }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate MCP Configurations
        run: |
          mkdir -p .gemini .opencode .qwen .claude
          
          # Basic Context7/Ref/Sequential MCP standard config
          cat << 'EOF' > mcp.json
          {
            "mcpServers": {
              "sequential-thinking": { "command": "npx", "args": ["-y", "@modelcontextprotocol/server-sequential-thinking"] },
              "context7": { "serverUrl": "https://mcp.context7.com/mcp", "headers": { "CONTEXT7_API_KEY": "\${{ secrets.CONTEXT7_API_KEY }}" } },
              "ref": { "serverUrl": "https://api.ref.tools/mcp", "headers": { "x-ref-api-key": "\${{ secrets.REF_API_KEY }}" } },
              "filesystem": { "command": "npx", "args": ["-y", "@modelcontextprotocol/server-filesystem", "/github/workspace"] },
              "github": { "command": "npx", "args": ["-y", "@modelcontextprotocol/server-github"], "env": { "GITHUB_TOKEN": "\${{ secrets.GITHUB_TOKEN }}" } }
            }
          }
          EOF
          
          cp mcp.json .gemini/settings.json
          cp mcp.json .opencode/config.json
          cp mcp.json .qwen/settings.json
          cp mcp.json .claude/settings.json
          
      - name: Run Gemini CLI
        if: inputs.agent_type == 'gemini'
        env:
          GEMINI_API_KEY: \${{ secrets.GEMINI_API_KEY }}
        run: |
          npm install -g @google/gemini-cli@latest
          gemini -p "\${{ inputs.prompt }}" --non-interactive

      - name: Run OpenCode
        if: inputs.agent_type == 'opencode'
        env:
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
        run: |
          curl -fsSL https://opencode.ai/install | bash
          opencode -p "\${{ inputs.prompt }}" -f json -q

      - name: Run Claude Code (via OpenRouter)
        if: inputs.agent_type == 'claude-code'
        env:
          ANTHROPIC_BASE_URL: https://openrouter.ai/api
          ANTHROPIC_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          ANTHROPIC_MODEL: \${{ inputs.openrouter_model }}
        run: |
          npm install -g @anthropic-ai/claude-code
          claude -p "\${{ inputs.prompt }}" --allowedTools "Read,Write,Edit,Bash"

      - name: Run Aider
        if: inputs.agent_type == 'aider'
        env:
          GEMINI_API_KEY: \${{ secrets.GEMINI_API_KEY }}
          GROQ_API_KEY: \${{ secrets.GROQ_API_KEY }}
        run: |
          pip install aider-chat --break-system-packages
          aider --model gemini/gemini-2.5-pro --message "\${{ inputs.prompt }}" --yes --no-git

      - name: Commit and Push Changes
        run: |
          git config --global user.name "repoflux-agent[bot]"
          git config --global user.email "repoflux-agent[bot]@users.noreply.github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generated by RepoFlux (\${{ inputs.agent_type }})"
            git push origin \${{ inputs.branch }}
          fi
`;

export async function checkWorkflowStatus(owner: string, repo: string, branch = 'main') {
  try {
    const file = await getFile(owner, repo, WORKFLOW_PATH, branch);
    return { installed: !!file, sha: file?.sha };
  } catch {
    return { installed: false };
  }
}

export async function installAgentWorkflow(owner: string, repo: string, branch = 'main', existingSha?: string) {
  const msg = existingSha ? 'Update RepoFlux Agent Workflow' : 'Install RepoFlux Agent Workflow';
  await writeFile(owner, repo, WORKFLOW_PATH, msg, WORKFLOW_YAML_TEMPLATE, branch, existingSha);
}
